# Pytype blacklist. Files will not be tested with pytype. Notice that the parse
# test will work for some of the files. Loading the files will fail, but is not
# tested at the moment.
# This file is also consumed by a bazel (https://github.com/bazelbuild/bazel)
# rule in another project. Therefore it needs to end in bzl and be valid bazel.
# The pytype_test.py in typeshed sees this file as a text file.

# This list was generated by importing the files with either python 2.7 or 3.6,
# depending on their directory.
# Files in 2and3 are blacklisted if they fail with at least one of the versions.

# pytype has its own version of these files. Which are imported by default,
# importing the same definitions again will result in name collisions.
stdlib/2/__builtin__.pyi
stdlib/2/builtins.pyi
stdlib/2/typing.pyi
stdlib/3/builtins.pyi
stdlib/3/typing.pyi

# AttributeError: 'UnionType' object has no attribute 'name'
stdlib/3.4/asyncio/subprocess.pyi
stdlib/3/fileinput.pyi
stdlib/3.4/asyncio/protocols.pyi
stdlib/3.4/asyncio/__init__.pyi
stdlib/3.4/asyncio/events.pyi

# Non resolvable imports
# imports non existing "builtins" module.
stdlib/2/os/__init__.pyi
# imports enum, which is undefined in Py2.7
stdlib/2and3/plistlib.pyi

# Unresolved dependencies
# BadDependencyError: Can't find pyi for 'RegexFlag', referenced from 're'
stdlib/3/re.pyi
# BadDependencyError: Can't find pyi for '4.asyncio.coroutines', referenced
# from '4.asyncio.locks'
stdlib/3.4/asyncio/locks.pyi
# BadDependencyError: Can't find pyi for '4.asyncio.futures', referenced from
# '4.asyncio.queues'
stdlib/3.4/asyncio/queues.pyi
# BadDependencyError: Can't find pyi for '4.asyncio.events', referenced from
# '4.asyncio.futures'
stdlib/3.4/asyncio/futures.pyi
# BadDependencyError: Can't find pyi for '4.asyncio.protocols', referenced
# from '4.asyncio.streams'
stdlib/3.4/asyncio/streams.pyi
# BadDependencyError: Can't find pyi for 'PlistFormat', referenced from
# 'plistlib'
stdlib/2and3/plistlib.pyi
# BadDependencyError: No Generator in module collections, referenced from
# 'collections.abc'
stdlib/3/collections/abc.pyi
# SymbolLookupError: Couldn't find ConnectionResetError in http.client
stdlib/3/http/client.pyi
# SymbolLookupError: Couldn't find AST in ast
stdlib/3/ast.pyi
# BadDependencyError: Duplicate top level items:
# 'concurrent.futures._base.Future, concurrent.futures._base.Future,
# concurrent.futures._base.Future', referenced from
# 'concurrent.futures.__init__'
stdlib/3/concurrent/futures/__init__.pyi
# BadDependencyError: Unreplaced NamedType: 'importlib.util'
stdlib/3/importlib/__init__.pyi
# BadDependencyError: No ChainMap in module typing, referenced from
# 'collections.__init__'
stdlib/3/collections/__init__.pyi
# BadDependencyError: Can't find pyi for 'Sigmasks', referenced from 'signal'
stdlib/3/signal.pyi
# SymbolLookupError: Couldn't find ConnectionResetError in http.client
stdlib/3/http/cookiejar.pyi
stdlib/3/urllib/request.pyi
# BadDependencyError: No _wrap_close in module os, referenced from 'pipes'
stdlib/3/pipes.pyi
# BadDependencyError: No stat_result in module os, referenced from 'posix'
stdlib/3/posix.pyi


# Conflicting values
# ContainerError: Conflicting values for TypeVar
# typing.ContextManager._T: multiprocessing.pool.Pool,
# multiprocessing.pool.ThreadPool
stdlib/3/multiprocessing/pool.pyi
stdlib/3/multiprocessing/context.pyi
stdlib/3/multiprocessing/process.pyi
stdlib/3/multiprocessing/__init__.pyi
stdlib/3/multiprocessing/synchronize.pyi

# pytype doesn't yet support aliases with implicit type parameters
# (e.g., here, FutureT = Future[T])
stdlib/3.4/asyncio/tasks.pyi

# BadDependencyError: No SupportsBytes in module typing, referenced from 'builtins'
stdlib/2and3/locale.pyi
stdlib/3/io.pyi
stdlib/3/calendar.pyi
stdlib/3/fcntl.pyi
stdlib/3/gzip.pyi
stdlib/3/os/path.pyi
stdlib/3/_compression.pyi
stdlib/3/tokenize.pyi
stdlib/3/os/__init__.pyi
stdlib/3/subprocess.pyi
