# new in py313
asyncio.unix_events.EventLoop
asyncio.unix_events._UnixSelectorEventLoop.create_unix_server
asyncio.unix_events.__all__
fcntl.F_GETNOSIGPIPE
fcntl.F_RDAHEAD
fcntl.F_SETNOSIGPIPE
mmap.MAP_HASSEMAPHORE
mmap.MAP_JIT
mmap.MAP_NOCACHE
mmap.MAP_NOEXTEND
mmap.MAP_NORESERVE
mmap.MAP_RESILIENT_CODESIGN
mmap.MAP_RESILIENT_MEDIA
mmap.MAP_TRANSLATED_ALLOW_EXECUTE
mmap.MAP_UNIX03
os.grantpt
os.posix_openpt
os.ptsname
os.unlockpt
os.waitid
os.waitid_result
pathlib.Path.group
pathlib.Path.owner
posix.grantpt
posix.posix_openpt
posix.ptsname
posix.unlockpt
posix.waitid
posix.waitid_result
readline.backend
webbrowser.MacOSX

# TODO: fix
_curses.unget_wch
_curses.window.get_wch
curses.window.get_wch

# These entries looks like a `setup-python` bug:
(dbm.gnu)?
(_?locale.bind_textdomain_codeset)?
(_?locale.bindtextdomain)?
(_?locale.dcgettext)?
(_?locale.dgettext)?
(_?locale.gettext)?
(_?locale.textdomain)?
